### ISSUE TITLE
Do players need additional setup?

### ISSUE THREAD

**Issue by pnxl** [HttpRafa/Modflared#10]
Hi there! I read on your README and Modrinth description that players do not need any additional setup.

> If your server admin has properly configured their server you should be able to connect to the server as usual. No extra configuration is needed.

But in the logs, I am receiving a message that says `[19:13:47] [Modflared Init Thread/ERROR]: No accessData to load found!`

Reading from other issues, this has led me to believe that you need an `access.json` file before trying to join the server. Do players need to set this up beforehand or is the mod supposed to set this up independently?

I am using version 0.1.2-1.20.1, which I am aware isn't the latest version - was automatic creation of the `access.json` file added recently?

**Comment by pnxl** [comment]
Update: I went ahead and updated my Fabric loader to 0.14.23 and updated to your 1.20.2 version of the mod 1.0.0, works now. Sorry!

**Comment by HttpRafa** [comment]
No problem, I still have to think about how I can avoid the risk of confusion between versions before 1.0.0 and 1.0.0 and later.
