### ISSUE TITLE
conflicts with ViaFabricPlus

### ISSUE THREAD

**Issue by HaeImCH** [HttpRafa/Modflared#12]
[04:34:59] [Render thread/WARN]:
` @Redirect conflict. Skipping viafabricplus.mixins.json:base.MixinConnectScreen_1 from mod viafabricplus->@Redirect::mapSocketAddress(Ljava/util/Optional;)Ljava/lang/Object; with priority 1000, already redirected by modflared.mixins.json:ConnectScreenMixin from mod modflared->@Redirect::connect(Ljava/util/Optional;)Ljava/lang/Object; with priority 1000`

hope this issue can be fixed. 🙏

**Comment by HaeImCH** [comment]
oops seems like i just mentioned random guy

**Comment by HttpRafa** [comment]
Which version of the mod are you using?

**Comment by HaeImCH** [comment]
hi, im using 1.0.0 with minecraft version 1.20.1
it works fine with new version of 1.1.0 beta3, guess ill just switch to 1.20.4 instead

**Comment by HttpRafa** [comment]
Since 1.20.4 is available, I will not update 1.20.1.

**Comment by HttpRafa** [comment]
If you have problems with 1.20.4, please feel free to contact me.
