### ISSUE TITLE
forge 1.20.1

### ISSUE THREAD

**Issue by edlo0** [HttpRafa/Modflared#13]
could you port to forge 1.20.1? some of the mods i would like to use with my friends haven't updated past 1.20.1.

**Comment by HttpRafa** [comment]
The old version is available for Forge 1.20.1. [Version](https://modrinth.com/mod/modflared/version/kTk5Zaml)

**Comment by edlo0** [comment]
i've tried that and this time i tried following the new instructions and it immediately gives me this screen when trying to connect to 127.0.0.1:25565
![image](https://github.com/HttpRafa/modflared/assets/28508286/88a99698-d217-4ea7-b51d-fcebbb2ca7f3)
and this is how it is set up 
![image](https://github.com/HttpRafa/modflared/assets/28508286/e99a5128-909c-4705-9607-5594ff7138f8)
![image](https://github.com/HttpRafa/modflared/assets/28508286/7ce091d8-c609-4739-bfe1-bf6ebb89be48)

**Comment by edlo0** [comment]
forgot this 
access.json
![image](https://github.com/HttpRafa/modflared/assets/28508286/cb214834-7f38-41d3-a5de-e3e87f62b5ee)

**Comment by HttpRafa** [comment]
Is it working?

**Comment by edlo0** [comment]
sorry i meant i forgot to add the screenshot of the json to the original comment. it doesnt work

**Comment by edlo0** [comment]
i forgot to put the mods into my mods folder when i redid everything... it works now
