### ISSUE TITLE
1.18.2 can't connect to server

### ISSUE THREAD

**Issue by TheMiniSandwich** [HttpRafa/Modflared#14]
**Describe the bug**

[Render thread/INFO] [modflared/]: Disconnecting from server, stopping cloudflared...
[Render thread/INFO] [modflared/]: Cloudflared stopped successfully
[Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to test.redacted.com, 25565
[Server Connector #2/INFO] [modflared/]: Connecting to test.redacted.com/redacted:25565
[Server Connector #2/INFO] [modflared/]: Using tunnel for test.redacted.com 
[Access#1/INFO] [modflared/]: [windows-amd64.exe access tcp --hostname test.redacted.com --url localhost:26345]
[Access#1/INFO] [Cloudflared/]: 2024-01-15T06:25:23Z INF Start Websocket listener host=localhost:26345
[Server Connector #2/ERROR] [net.minecraft.client.gui.screens.ConnectScreen/]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:26345
Caused by: java.net.ConnectException: Connection refused: no further information

I have a tunnel correctly configured, can connect over cloudflared on client.
I can connect via 127.0.0.1:26345 to the server. localhost:26345 does not work.
I am currently using forced_tunnels.json, however I have added to correct CNAME and TXT DNS records on subdomain "test" with value "cloudflared-use-tunnel"

**Which version of the mod/game are you using?**
Minecraft: Forge 1.18.2
Mod Version: 1.0.0 Alpha

**To Reproduce**
1. Start game
2. Click on multiplayer
3. Add server "test.redacted.com"
4. Add server "localhost: _whatever modflared gives you_ "
5. Add server "127.0.0.1: _whatever modflared gives you_ "
6. See error

**Expected behavior**
test.redacted.com has a connection

**Screenshots**
Available if asked for, will have to redact information

**Additional context**
Tried looking through other issues but the only 1.18.2 issue had a similar problem but was marked complete due to a lack of response, hoping to work through the issue. I think it might have to due with forge and an inability to connect to localhost, only 127.0.0.1, but maybe that's a me problem

**Comment by HttpRafa** [comment]
Because of this issue I changed the address in the new versions to 127.0.0.1. If I get home I will make an update that changes it to 127.0.0.1. Hopefully this fixes that issue.

**Comment by HttpRafa** [comment]
I uploaded a new version can you check if it now works. [Version](https://modrinth.com/mod/modflared/version/1.0.0-hotfix)

**Comment by TheMiniSandwich** [comment]
I am now getting stuck at "encrypting". I can see that I attempt to join the server, but I eventually just time out.

**Comment by HttpRafa** [comment]
That's normal when using Cloudflare tunnels for playing Minecraft. You can try restarting Cloudflared on the server.

**Comment by TheMiniSandwich** [comment]
never had the issue running cloudflared directly on the client, ill try a few more times though

**Comment by TheMiniSandwich** [comment]
was able to connect running cloudflared on the host (cloudflared access tcp --hostname test.redacted.com --url 127.0.0.1:25565), but cannot connect via "test.redacted.com" through modflared, keeps getting stuck at encrypting and timing out. Is there any good way to fix this?

**Comment by HttpRafa** [comment]
The problem is that I don't know exactly why this problem occurs. For me the error occurred for 5 minutes and disappeared again without any changes made.

**Comment by TheMiniSandwich** [comment]
Got it, looks like the connection at least works to a degree. I can make a separate ticket if I continue to never connect. EDIT: Got a connection after a few more attempts, I guess the best thing to do is have the mod and the option to use cloudflared directly if players are having issues. Thanks for the help and quick turn around on fixes
