### ISSUE TITLE
What is the proper installation of modflared?

### ISSUE THREAD

**Issue by TitanGames-729** [HttpRafa/Modflared#15]
**Describe the bug**
I tried to set up a tunnel using cloudflare zero tunnel but i can't connect to my server

**Which version of the mod/game are you using?**
Fabric 1.19.4

**To Reproduce**
I think it will be helpfull to mention all steps i ve gone trough:
1. I've put the modflared in the mods folder. After minecraft's start i could not find any config file, so i have **not** configured anything since i will configure my DNS to add the txt record. 
2. I have my domain in cloudflare, i ve set up the zero tunnel (choose name, put your card [you wont be charged for that, if free is chosen]) . After creating the tunnel, i ve created the public hostname with these values:
**Subdomain**         **Domain(Required)**         **(optional) path**
play                       .      mydomain.com           / 

Service
**Type**(Required)                  **URL**(Required)
TCP                             ://             localhost:25565      (i ve had my machine's internal ip but it didnt work, then have tried the 127.0.0.1 and localhost, also set them in server.properties but no luck )

3. i have installed cloudflared on my ubuntu server LTS but it was buggy (path issues and so on) so i have chosen the cloudflared trough docker. I installed the docker with the command given in the tunnel's settings.
4, i've set up the TXT dns record with these values:
**name**                                                                          **content**
(the same as i set for the public hostname)
play                                                                         cloudflared-use-tunnel

The CNAME record was created automatically after creating the tunnel.

**Expected behavior**
Connection to the server

**Screenshots**

**Additional context**
I've checked the docker logs and it has been receiving the config values:
- hostname: play.mydomain.com
  service: tcp://whateverlocalhost:25565

I've set up the server's map which uses the HTTP, using the same method and it worked. The URL in the public hostname was my machine's internal IP.

So, on this step i am pretty confused why it does not working, i tried using cloudflared manually: cloudflared-windows-amd64.exe access tcp --hostname play.mydomain.com --url (My machine's IP [ERROR] , localhost, 127.0.0.1,):25565
It will show something like:
Start Websocket listener 
but it wont connect.

**Comment by TitanGames-729** [comment]
It works when i use manually:
cloudflared-windows-amd64.exe access tcp --hostname play.mydomain.com --url 127.0.0.1:25565
and i connect to the localhost or 127.0.0.1.

Why ? It supposed to work from play.mydomain.com isn't it?
Maybe the the access.json config is required as
`[Modflared Init Thread/ERROR]: No accessData to load found!`

**Comment by HttpRafa** [comment]
It is important that you connect to 127.0.0.1 in Minecraft. Because when you start the game, the mod only executes the command that you executed yourself(```cloudflared-windows-amd64.exe access tcp --hostname play.mydomain.com --url 127.0.0.1:25565```).

**Comment by HttpRafa** [comment]
Because you are using a version below 1.0.0 you have to create the access.json.

**Comment by TitanGames-729** [comment]
> It is important that you connect to 127.0.0.1 in Minecraft. Because when you start the game, the mod only executes the command that you executed yourself(`cloudflared-windows-amd64.exe access tcp --hostname play.mydomain.com --url 127.0.0.1:25565`).


> Because you are using a version below 1.0.0 you have to create the access.json.


ohhhh, that explains a lot. Just the phrase "If your server admin has properly configured their server you should be able to connect to the server **as usual.** " had me confused.
