### ISSUE TITLE
Pinging tunneled server failing

### ISSUE THREAD

**Issue by JonasunderscoreJones** [HttpRafa/Modflared#18]
**Is your feature request related to a problem? Please describe.**
Pinging a server in the Multiplayer Screen (getting ping, player count, server motd) doesn't work (probably a feature request and not a bug)

**Describe the solution you'd like**
Add support for this

**Describe alternatives you've considered**
PR myself if I have the time

**Additional context**
latest version from modrinth

**Comment by HttpRafa** [comment]
Support for pinging a tunneled server was added in this [commit](https://github.com/HttpRafa/modflared/commit/3cf5e7d88276572cacd6646cd1d5f2e83def6ed7). This should be available in versions over 1.0.0.

**Comment by JonasunderscoreJones** [comment]
cool, works. thank you very much!
