### ISSUE TITLE
1.16.5 support

### ISSUE THREAD

**Issue by amcheter** [HttpRafa/Modflared#19]
Hi, is it possible to add support for (forge) 1.16.5? A lot of the mods I like are for 1.16.5, and this mod would allow me to play with my friends easily. Thanks!

**Comment by HttpRafa** [comment]
I'll have a look next week and port the mod to 1.16.5 for you. I have a lot to do at the moment.

**Comment by HttpRafa** [comment]
I'm sorry you had to wait so long but I have ported the mod to 1.16.5 you can download it [here](https://modrinth.com/mod/modflared/versions?c=release&g=1.16.5&l=forge). If you find bugs, feel free to file a bug report.
