### ISSUE TITLE
Can someone make an indepth .README file 

### ISSUE THREAD

**Issue by esraell** [HttpRafa/Modflared#2]
would be cool if someone can make directions on how to install and configure this mod, also how to configure it using docker

**Comment by HttpRafa** [comment]
I will add the description I wrote on [Modrinth](https://modrinth.com/mod/modflared)

**Comment by HttpRafa** [comment]
What do you mean with docker. How to setup the tunnel itself?

**Comment by esraell** [comment]
Yeah just a good guide on how to install the tunnel for first time users, cuz i was a bit confused at first

**Comment by HttpRafa** [comment]
When I have time I will do it. Or if someone else wants to do it, they can do it too.
