### ISSUE TITLE
Modflared with MC server running in docker

### ISSUE THREAD

**Issue by SneakyISausage** [HttpRafa/Modflared#22]
**Describe the bug**
I tried installing modflared on my server. I managed to use ngrok but since the free version only allows 1GB of monthly traffic, it won't work for me.
Your mod seems very usefull, but I have a hard time setting it up properly.

**Which version of the mod/game are you using?**
Where did you get the version from? Which Minecraft version do you use? Which mod version are you using?
I am using minecraft version 1.20.1 with the "all the mods 9 - ATM". It is a forge modpack.

**To Reproduce**
1. Install MC server (itzg/minecraft-server:latest) running in a docker container.
2. Install ATM9(version 0.2.46) on the server and also install missing mods manually.
3. Run the ATM9 to test if server is running properly on local network
4. Install Cloudflare Tunnel on Server(it is running fine I assume, since the dashboard shows it as healthy)
5. also configured the tunnel with the help of the provided template
6. I installed architectury-API(dependency mentioned in the docs) on a TestProfile in CurseForge and also added the modflared mod in the mods folder to this Profile.
7. I set up the modflared fodler with the path C:/Users/myuser/curseforge/minecraft/modflared and in that folder the access.json with the template provided in the docs. I change the domain, to the one I own
8. Start the TestProfile

**Expected behavior**
I should be able to see my mcserver on the domain I provided, but simultaneously see an error of missing mods(since ATM9 is not installed on this profile)

**Screenshots**
I can show it to you live, since I am based in Germany too. If you are available sometime.

**Additional context**
Thanks in advance.

**Comment by SneakyISausage** [comment]
You can close this bug. A kind Reddit user help me fix the things I messed up. It works now.

**Comment by HttpRafa** [comment]
Ok, that's nice to hear 😊

**Comment by TheKing349** [comment]
> You can close this bug. A kind Reddit user help me fix the things I messed up. It works now.

What was the issue? I'm running into the same problem. I'm using the same minecraft server docker container and cannot figure it out

**Comment by SneakyISausage** [comment]
Sorry for my super late answer. I messed up the access.json at some point and it wrecked the whole thing. 

Did your issue resolve?

**Comment by TheKing349** [comment]
> Sorry for my super late answer. I messed up the access.json at some point and it wrecked the whole thing.
> 
> Did your issue resolve?

No you're good! I did, I ended up having to do a weird, convoluted thing where I have two tunnels with DNS records, where one points to another. I found a guide somewhere(idk if it was this GitHub page or another place) and after messing around with it I finally figured it out
