### ISSUE TITLE
1.12.2 Support

### ISSUE THREAD

**Issue by 0xfossman** [HttpRafa/Modflared#3]
I have made a custom modpack on 1.12.2 and I would like to tunnel my minecraft server to my friends. This would make perfect sense.

**Comment by HttpRafa** [comment]
Are you using Fabric or Forge?

**Comment by HttpRafa** [comment]
If you use Fabric: [New Version for 1.20.2](https://modrinth.com/mod/modflared/version/0.1.3)

**Comment by 0xfossman** [comment]
i don't think you understand what I mean. I meant adding support for Minecraft 1.12.2, there is no fabric build for that version.

**Comment by HttpRafa** [comment]
😂 Backporting the mod for 1.12.2 shouldn't be difficult.  I'll get to it today or tomorrow.

**Comment by 0xfossman** [comment]
okay thanks😄

Gesendet mit Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by HttpRafa** [comment]
Done :) [New Version](https://modrinth.com/mod/modflared/version/Wy1cfBCz)
If you don't find any problems you can close this issue. If not I will close it after a while.

**Comment by 0xfossman** [comment]
I'll test it a bit and see if it's working, thx !

**Comment by 0xfossman** [comment]
Testing done, ping hovers around 250 to 280 ms but I guess this is a cloudflare thing or because of my network. Still it works so i'll close this.
Danke fürs porten großer!
