### ISSUE TITLE
Modflared does not function when using a steamdeck

### ISSUE THREAD

**Issue by Ranses969** [HttpRafa/Modflared#31]
**Describe the bug**

Modflared tunnel does not function on Fabric Modloader when Using SteamOS.

**Which version of the mod/game are you using?**
1.20.4
1.2.0 for mod

**To Reproduce**
1. Start game
2. Click on multiplayer
3. Click on "Join Game"
4. Minecraft will present the error below. A ss has been provided. 

5. See error
"Failed to connect to server"
Cannot invoke "de.rafael.modflared.tunnel.RunningTunnel.access()"
"de.rafael.modflared.tunnel.TunnelStatus.runningTunnel()" is null

**Expected behavior**
Modflared tunnel works by showing the indicator logo on the Minecraft server menu screen. Connection is possible due to Modflared. 

**Screenshots**
![Screenshot 2024-05-07 232202](https://github.com/HttpRafa/modflared/assets/138336225/31b501b0-38d5-413f-acf0-2dbd0e1544b7)

**Additional context**
This mod functions via Win11 without client modification. Server side configuration is correct and clients do not need to change modflared settings to access the server when using Win11. Multiple users use this server consistently using ONLY modflared. 
I attempted using SteamOS Desktop and SteamOS default configuration.
I attempted to force IPv4 connection by disabling IPv6 in SteamOS desktop settings.
Singe player worlds function as expected on SteamDeck. 
Modrinth is beiung used to launch Minecraft. 
The Server is ran on Debian12 within a crafty docker container over IPV4

The following is my latest.log from crafty
[latest.log](https://github.com/HttpRafa/modflared/files/15243506/latest.log)

**Comment by HttpRafa** [comment]
Is it possible that you can send me the logs of the client? Then I could better narrow down the error.
