### ISSUE TITLE
NullPointerException while still downloading cloudflared

### ISSUE THREAD

**Issue by cacklinglaughing** [HttpRafa/Modflared#32]
**Describe the bug**
Random nullpointer exception java.lang.NullPointerException: null when you try to join a server before cloudflared downloads

**Which version of the mod/game are you using?**
1.16.5 1.2.0+49

**To Reproduce**
Install modflared, have it say `Downloading cloudflared version 2024.5.0 from github. Attempt: 1` then try and join a server

**Expected behavior**
I would suggest having a message that says we're still downloading cloudflared

**Additional context**
This stopped happwning after `Download finished of cloudflared version 2024.5.0!` showed up

**Comment by HttpRafa** [comment]
Yeah, I'll take a look at it tomorrow.

**Comment by cacklinglaughing** [comment]
Thank you. This expected behavior is kind of just a suggestion but it might help someone out later who didn't read the logs and doesn't know cloudflared is downloading.
