### ISSUE TITLE
Update for 1.21?

### ISSUE THREAD

**Issue by afratera** [HttpRafa/Modflared#42]
Will this mod get an update for Version 1.21+? 

If the current build (1.2.1+release.55 for 1.20.6 (Fabric))is used, Minecraft Crashes when opening the Multiplayer screen.

**Comment by HttpRafa** [comment]
I'll start updating tomorrow. Unfortunately, I don't have much time at the moment.

**Comment by HttpRafa** [comment]
Closed by https://github.com/HttpRafa/modflared/commit/25433dfb629729ff832f9f2f7c16a6ec31006660
