### ISSUE TITLE
Port Not Randomized

### ISSUE THREAD

**Issue by Pixyde** [HttpRafa/Modflared#51]
Would it be possible to make it so the client always connect using the same port ?
I'm trying to use AutoModpack but it seems to reconize everyport as a different modpack.

**Comment by HttpRafa** [comment]
Yes that would be possible but I would make it behind a switchable feature. I'll take care of it this weekend.

**Comment by Pixyde** [comment]
tysm

**Comment by HttpRafa** [comment]
Which Minecraft version do you need it for?

**Comment by Pixyde** [comment]
1.18.2 and if possible for a friend 1.19.2

**Comment by HttpRafa** [comment]
I've set it up so that the port depends on the address, meaning the same address equals the same port. This should fix the issue. If you encounter any further problems, feel free to reach out to me.

**Comment by CaptainGolem** [comment]
I need it for 1.21.1 too please. Thanks!
