### ISSUE TITLE
Porting to 1.18.2

### ISSUE THREAD

**Issue by mpamop** [HttpRafa/Modflared#6]
Hello, i'm created modpack on my home server, and i rid of programs for lan tunnelling. I found this mod, and want see on 1.18.2 version. Can you please port this mod?

**Comment by mpamop** [comment]
Forgot to add, mod for Forge 1.18.2

**Comment by HttpRafa** [comment]
I'll work on it in the next few days.

**Comment by mpamop** [comment]
If cloudflared installed already configured, mod will be use it, or it uses other method?

**Comment by HttpRafa** [comment]
The mod will always download its own binary file. The only thing the user has to do is create the json file.

**Comment by 0xfossman** [comment]
> If cloudflared installed already configured, mod will be use it, or it uses other method?

I don't know if you can run 2 cloudflared tunnels from one machine but since you are only accessing a tunnel it should work. Test it and report the results

**Comment by HttpRafa** [comment]
It should now work on Minecraft version [1.18.2](https://modrinth.com/mod/modflared/version/XcPFEOsw). Unfortunately, I don't have a Cloudflared test server, so I couldn't test it. If you find any problems, please feel free to reopen the issue.

**Comment by mpamop** [comment]
Thanks for porting mod, but it seems not work. I have setted up access.json in modflared folder, configured default config.yml, mod downloaded binary, but it dont start (im checked manually, it work).
In server logs 

> [modloading-worker-0/ERROR] [modflared/]: No accessData to load found!

what i do wrong?

in access.json

![изображение](https://github.com/HttpRafa/modflared/assets/37378280/36e7b973-0c0a-4d3d-9189-ebc4be9f6c8f)

**Comment by HttpRafa** [comment]
I ported the 1.20.2 1.0.0 version to 1.18.2.  This version no longer uses access.json.  You can find a description of the new version on the [Modrinth](https://modrinth.com/mod/modflared) page.  If something doesn't work or you have questions, just post them in this issue.

**Comment by mpamop** [comment]
It doesnt start tunnel, on zerotrust dashboard tunnel is down, but i can manually set it up by command 

> cloudflared tunnel run

But it does nothing, client cant connect to server anyway

**Comment by HttpRafa** [comment]
You have to set up the tunnel so that it appears as UP in your Zero Trust dashboard. Then you have to add the DNS record for the Tunnel CNAME -> "#tunnelID#.cfargotunnel.com". Then you have to create a TXT-DNS entry with the value “cloudflared-use-tunnel” and the same sub-domain. When everything is done you can start your Minecraft and enter the DNS name for your tunnel CNAME entry “example.mydomain.com”. NOTE: The server's MOTD is not visible!

[How to create a tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/)
[Cloudflare Wiki](https://developers.cloudflare.com/cloudflare-one/applications/non-http/arbitrary-tcp/)
[What Modflared does for you](https://developers.cloudflare.com/cloudflare-one/applications/non-http/arbitrary-tcp/#connect-from-a-client-machine)

**Comment by HttpRafa** [comment]
> Thanks for porting mod, but it seems not work. I have setted up access.json in modflared folder, configured default config.yml, mod downloaded binary, but it dont start (im checked manually, it work). In server logs
> 
> > [modloading-worker-0/ERROR] [modflared/]: No accessData to load found!
> 
> what i do wrong?
> 
> in access.json
> 
> ![изображение](https://private-user-images.githubusercontent.com/37378280/287530879-36e7b973-0c0a-4d3d-9189-ebc4be9f6c8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NDE1MzUsIm5iZiI6MTcwMTY0MTIzNSwicGF0aCI6Ii8zNzM3ODI4MC8yODc1MzA4NzktMzZlN2I5NzMtMGMwYS00ZDNkLTkxODktZWJjNGJlOWY2YzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDIyMDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNDkyZmMxMjNlYTYzMGY1YWU0NTcwNzljYWFiNmFkYzc3MzRiMDBhZGM0MTcxZmIyMTg3YzBhNzk3NTljMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Qcu9soIYUioGlAM6h0oAPXaX3bF-L3Q8yGROsGOLr4)

Please note that Modflared is not a server mod but a mod that allows the client to easily connect to the server. Cloudflared must be set up manually by the server admin.

**Comment by mpamop** [comment]
ok, i setted up cname and txt on same subdomain, setted up tunnel to my local ip with default port 25565, but it didnt connect.
![изображение](https://github.com/HttpRafa/modflared/assets/37378280/dc9449a1-dbd9-4b6a-a81c-f531e1561b55)
![изображение](https://github.com/HttpRafa/modflared/assets/37378280/6110ea35-606a-4488-9653-ca5df83171cf)


here logs from client

>> [09:40:16] [Render thread/INFO] [minecraft/ConnectScreen]: Connecting to minec.mydomain, 25565
>> [09:40:16] [Server Connector #1/INFO] [modflared/]: Connecting to minec.mydomain/someip:25565
>> [09:40:16] [Server Connector #1/INFO] [modflared/]: Using tunnel for minec.mydomain
>> [09:40:16] [Access#0/INFO] [modflared/]: [windows-amd64.exe access tcp --hostname minec.mydomain --url localhost:27095]
>> [09:40:16] [Access#0/INFO] [Cloudflared/]: 2023-12-04T04:40:16Z INF Start Websocket listener host=localhost:27095
>> [09:40:17] [Server Connector #1/ERROR] [minecraft/ConnectScreen]: Couldn't connect to server
>> io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:27095
>> Caused by: java.net.ConnectException: Connection refused: no further information

in ZeroTrust tunnel is up, tcp connection

**Comment by HttpRafa** [comment]
Can you run the command ```windows-amd64.exe access tcp --hostname minec.mydomain --url localhost:27095``` in the Modflared bin folder and then try to join the server with localhost:27095?

**Comment by mpamop** [comment]
It start listening, but it didnt connect...
checked http tunnel, cloudflared works, but tcp cant

**Comment by mpamop** [comment]
I'm trying to do everything on my local machine, maybe later I'll try to connect through a friend, maybe that will work....

**Comment by HttpRafa** [comment]
Any updates? I will try to reproduce this issue on my setup over the next days.

**Comment by HttpRafa** [comment]
I tested it again on my setup and it worked without any problems. I have uploaded screenshots of the DNS and tunnel settings.
![dns1](https://github.com/HttpRafa/modflared/assets/60099368/67532aea-7f9c-4723-83cf-06b9c484ba1e)
![dns2](https://github.com/HttpRafa/modflared/assets/60099368/cebe4333-0c86-4c13-b707-c3036844638f)
![tunnel](https://github.com/HttpRafa/modflared/assets/60099368/1be62b30-15a7-4479-ae3a-910c95b4dfc4)

**Comment by mpamop** [comment]
![Screenshot_20231210-104519_Firefox~2.png](https://github.com/HttpRafa/modflared/assets/37378280/b2fbbde9-d293-4eb3-8c4d-16862d4f675c)

![Screenshot_20231210-104621_Firefox~2.png](https://github.com/HttpRafa/modflared/assets/37378280/3266dec5-c822-4a7c-b701-b8b98d369aff)

![Screenshot_20231210-104859_Firefox~2.png](https://github.com/HttpRafa/modflared/assets/37378280/6d725fb2-0cb8-4b25-9c8f-d4ae78ddfc37)

I tested again with tunnel on localhost, 127.0.0.1 and received ip from router

Ill try bit later on a vps

**Comment by HttpRafa** [comment]
Any updates?

**Comment by mpamop** [comment]
Many days and nothing, idk what im doing wrong, tried many variations, reinstalled cloudflared, rewrite config on cli, created many tunnels on dashboard...
