### ISSUE TITLE
forced tunnel only works for me

### ISSUE THREAD

**Issue by thesavagen** [HttpRafa/Modflared#9]
I have used modflared on version 1.19.3 and 1.20.1 where it was required to use the access.json file for joining. I glad you where able to shorten it down to only the domain. However I am interested in setting up to where that file is not working. I tried to add the config file under my programs file and it didn't change anything. I am on windows btw idk if its different for windows. Thanks in advance.

**Comment by HttpRafa** [comment]
Did you add the file relative to the Minecraft folder? #MinecraftFolder#/modflared/forced_tunnels.json. If the file is not in this location the mod cannot find it.

**Comment by thesavagen** [comment]
I did and that worked but it sounded like there was a way to have it
connect without one?

**Comment by HttpRafa** [comment]
In order for the mod to know to use a Cloudflare tunnel, you need to create a DNS entry on the same domain with the same subdomain as the server.  In the end you need 2 DNS entries a CNAME (with the tunnel ID) and a TXT (with "cloudflared-use-tunnel").  If both entries are present the mod should connect you.

**Comment by thesavagen** [comment]
I created my cname through the stuff in zero trust and I setup the txt dns with the cloudflared-route=example.domain.net (put my domain in it)

**Comment by HttpRafa** [comment]
Do you get message in console like "Using tunnel for ..." when you join the server.

**Comment by thesavagen** [comment]
This is what my logs say. 
Note: I changed domain name and IP's All ips are the same all domain names are the same

Here it is: 


23:32:46.798
modflared
Render thread
Cloudflared stopped successfully
23:32:46.800
net.minecraft.class_412
Render thread
Connecting to test.domain.net, 25565
23:32:46.805
modflared
Server Connector #1
Connecting to test.domain.net/192.168.5.5:25565
23:32:46.807
modflared
Server Connector #1
Not using tunnel for test.domain.net
23:33:07.858
net.minecraft.class_412
Server Connector #1
Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: test.domain.net/192.168.5.5:25565
Caused by: java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by HttpRafa** [comment]
> This is what my logs say. Note: I changed domain name and IP's All ips are the same all domain names are the same
> 
> Here it is:
> 
> 23:32:46.798 modflared Render thread Cloudflared stopped successfully 23:32:46.800 net.minecraft.class_412 Render thread Connecting to test.domain.net, 25565 23:32:46.805 modflared Server Connector #1 Connecting to test.domain.net/192.168.5.5:25565 23:32:46.807 modflared Server Connector #1 Not using tunnel for test.domain.net 23:33:07.858 net.minecraft.class_412 Server Connector #1 Couldn't connect to server io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: test.domain.net/192.168.5.5:25565 Caused by: java.net.ConnectException: Connection timed out: no further information at java.base/sun.nio.ch.Net.pollConnect(Native Method) at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at java.base/java.lang.Thread.run(Thread.java:833)

I'll sit down this weekend and see if I can reproduce your problem. But it looks like Modflared doesn't recognize your TXT-Dns entry.

**Comment by thesavagen** [comment]
Just to make sure that it wasn't the txt files I tried the following:

play as the title then cloudflared-use-tunnel.
cloudflared-use-tunnel as title and test as content. 
as title cloudflared-route=play.exampledomain.net and test as content
play as title and cloudflared-route=play.exampledomain.net as content

**Comment by HttpRafa** [comment]
I will try to reproduce this issue on my setup over the next days.

**Comment by HttpRafa** [comment]
I tested it again on my setup and it worked without any problems. I have uploaded screenshots of the DNS and tunnel settings.
![dns1](https://github.com/HttpRafa/modflared/assets/60099368/67532aea-7f9c-4723-83cf-06b9c484ba1e)
![dns2](https://github.com/HttpRafa/modflared/assets/60099368/cebe4333-0c86-4c13-b707-c3036844638f)
![tunnel](https://github.com/HttpRafa/modflared/assets/60099368/1be62b30-15a7-4479-ae3a-910c95b4dfc4)

**Comment by HttpRafa** [comment]
Any updates?

**Comment by thesavagen** [comment]
That worked. Sorry I didn't understand the naming convention. But after setting that stuff making it look like that it worked. Thank you! I think those screenshots could be helpful in the instructions.

**Comment by HttpRafa** [comment]
I generally need to make the description more precise, but I don't have enough time to do this at the moment. If I find free time, I'll revise it.
